### ISSUE TITLE
MXBoard warning

### ISSUE THREAD

**Issue by jsedoc** [kevinduh/sockeye-recipes#20]
Hi,

I'm getting the following warning (see below). Does anyone know if this is serious? Should I use a compatible version? Which one?

[WARNING:root] The currently installed MXNet version 1.1.0 is less than 1.2.0. Some functionality of MXBoard may not work.

**Comment by kevinduh** [comment]
It should be ok. Training/decoding should run as usual. We'll update the install scripts later so that mxboard visualization is re-enabled.

**Comment by kevinduh** [comment]
We've updated the install scripts and Tensorboard visualization is now supported again. 
See commit: https://github.com/kevinduh/sockeye-recipes/commit/a5d80c2e34bb2db8953f0063aaac5f82b59ed50b
