### ISSUE TITLE
train-alloptions.sh  is missing from scripts.

### ISSUE THREAD

**Issue by noisychannel** [kevinduh/sockeye-recipes#27]

**Comment by kevinduh** [comment]
Yes, it's no longer needed and deprecated. Beforehand, `train-alloptions.sh` was a quick solution to deal with the fact that `train.sh` focused on a subset of RNN options. Now, `train.sh` has be updated to work with RNN, Transformer, and CNN architectures (by calling `model-specific-args`). 

I just noticed we forgot to update `egs/ted/README.md` to say this, and will do so soon.
